pmic_basin_cove: Fix the build error
BZ: 147007

The commit fd50cc3aefbe1c02aec3a2b9ed866b61771c0852 has moved away the
ipc definitions from the original upstream commit
fd50cc3aefbe1c02aec3a2b9ed866b61771c0852. This has caused below build
error for this driver. Fix it

  CC      drivers/regulator/pmic_basin_cove.o
drivers/regulator/pmic_basin_cove.c: In function 'intel_pmic_reg_is_enabled':
drivers/regulator/pmic_basin_cove.c:52:2: error: implicit declaration of function 'intel_scu_ipc_ioread8'
drivers/regulator/pmic_basin_cove.c: In function 'intel_pmic_reg_enable':
drivers/regulator/pmic_basin_cove.c:79:2: error: implicit declaration of function 'intel_scu_ipc_iowrite8'

Change-Id: I8642b7222783ff4fc05926316bc44dc920b44c56
Reported-by: Ziyu Jiang <ziyux.jiang@intel.com>
Signed-off-by: Srinidhi Kasagar <srinidhi.kasagar@intel.com>
Reviewed-on: http://android.intel.com:8080/138894
Reviewed-by: Mansoor, Illyas <illyas.mansoor@intel.com>
Reviewed-by: Nordell, Joakim <joakim.nordell@intel.com>
Tested-by: Cuesta, Fernand <fernand.cuesta@intel.com>
Reviewed-by: cactus <cactus@intel.com>
Tested-by: cactus <cactus@intel.com>