ASoC: intel: Add custom mic id callback for WM8958
BZ: 139640

Add custom mic id routine to allow partial insert of headset
with  complete insertion after some indeterminate time.

Ported from K3.4 BZ: 121325
Fix compilation error: Use pdata cached in mfd driver

Orig-Change-Id: I449616f617ff9146c166d33c52e6494f5080a18c
Signed-off-by: Nariman Poushin <nariman@opensource.wolfsonmicro.com>
Reviewed-on: http://android.intel.com:8080/119588
Reviewed-by: Nilofer, Samreen <samreen.nilofer@intel.com>
Reviewed-by: B, Jayachandran <jayachandran.b@intel.com>
Reviewed-by: Kp, Jeeja <jeeja.kp@intel.com>
Reviewed-by: Koul, Vinod <vinod.koul@intel.com>
Tested-by: Gupta, ArvindX K <arvindx.k.gupta@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>
(cherry picked from commit f58243ffe9f3aacb0157c15a82bb155f714ee680)

Change-Id: I1e5a981b42829687b3c5fac2a6f2b6e9baa8ef58
Signed-off-by: Subhransu S. Prusty <subhransu.s.prusty@intel.com>
Reviewed-on: http://android.intel.com:8080/133334
Reviewed-by: Koul, Vinod <vinod.koul@intel.com>
Reviewed-by: Yang, Fei <fei.yang@intel.com>
Reviewed-by: Shah, Hardik T <hardik.t.shah@intel.com>
Tested-by: Koyili, SrikanthX <srikanthx.koyili@intel.com>
Reviewed-by: cactus <cactus@intel.com>
Tested-by: cactus <cactus@intel.com>