CONFIG: Enable CONFIG_BACKLIGHT_LP855X
BZ: 150294

Enable CONFIG_BACKLIGHT_LP855X which is required for baytail targets.
The option has already been enabled for 32bit kernel, but missed out for
64bit kernel. And that was causing following compile error,
function intel_panel_enable_backlight: error: undefined reference to 'lpdata'

Change-Id: I4c6532770e548f9927fef8f6b867c6542950c490
Signed-off-by: Fei Yang <fei.yang@intel.com>